import { useState } from 'react'
import { ChevronLeft, ChevronRight, Dumbbell, Image, Scale, Utensils } from 'lucide-react'
import { useApp } from '../data/context'
import { Panel, SectionHead } from '../components/shared'
import { Button } from '../components/ui/button'
import { dateKey, dateLabel, formatNumber, todayKey } from '../lib/utils'
import { tr } from '../lib/i18n'

export function CalendarPage({ onDay }: { onDay: (date: string) => void }) {
  const { data } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [view, setView] = useState(() => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1) })
  const firstOffset = (view.getDay() - s.weekStart + 7) % 7, monthDays = new Date(view.getFullYear(), view.getMonth() + 1, 0).getDate()
  const headers = Array.from({ length: 7 }, (_, i) => new Intl.DateTimeFormat(s.language === 'ar' ? 'ar-IQ' : 'en-US', { weekday: 'short' }).format(new Date(2024, 0, 7 + (s.weekStart + i) % 7)))
  const byDate = new Map(data.days.map(d => [d.date, d]))
  const photos = new Set(data.photos.map(p => p.date))
  const move = (n: number) => setView(new Date(view.getFullYear(), view.getMonth() + n, 1))
  return <div className="page-enter"><SectionHead eyebrow={t('DAY BY DAY')} title={t('Calendar')} description={t('A clear view of every check-in, rest day, and weigh-in.')} /><Panel className="p-3 sm:p-6"><div className="mb-5 flex items-center justify-between px-2"><Button variant="ghost" size="icon" onClick={() => move(-1)} aria-label="Previous month"><ChevronLeft size={18} /></Button><h2 className="text-lg font-bold">{dateLabel(dateKey(view), s.language, { month: 'long', year: 'numeric' })}</h2><Button variant="ghost" size="icon" onClick={() => move(1)} aria-label="Next month"><ChevronRight size={18} /></Button></div><div className="grid grid-cols-7 text-center">{headers.map((h, i) => <div key={i} className="pb-3 text-[11px] font-bold uppercase text-muted">{h}</div>)}{Array.from({ length: firstOffset }, (_, i) => <div key={`blank-${i}`} />)}{Array.from({ length: monthDays }, (_, i) => { const day = i + 1, key = dateKey(new Date(view.getFullYear(), view.getMonth(), day)), d = byDate.get(key); return <button key={key} onClick={() => onDay(key)} className={`group relative m-0.5 flex min-h-18 flex-col items-start rounded-xl border p-2 text-start transition-colors sm:min-h-25 sm:p-3 ${key === todayKey() ? 'border-accent/70 bg-accent/5' : 'border-line hover:border-accent/60 hover:bg-surface-2'}`}><span className={`text-xs font-semibold ${key === todayKey() ? 'text-accent' : ''}`}>{formatNumber(day, s.language)}</span><div className="mt-auto flex flex-wrap gap-1.5">{d?.gym === 'completed' && <Dumbbell size={13} className="text-accent" />}{d?.gym === 'rest' && <span className="h-2 w-2 rounded-full bg-muted" title={t('Rest day')} />}{d?.gym === 'missed' && <span className="h-2 w-2 rounded-full bg-danger" title={t('Missed day')} />}{d?.diet === 'followed' && <Utensils size={13} className="text-diet" />}{d?.diet && d.diet !== 'followed' && <Utensils size={13} className="text-danger" />}{d?.weightKg !== undefined && <Scale size={13} className="text-weight" />}{photos.has(key) && <Image size={13} className="text-photo" />}</div></button> })}</div></Panel><div className="mt-4 flex flex-wrap gap-4 text-xs text-muted"><span className="flex items-center gap-1"><Dumbbell size={13} className="text-accent" /> {t('Gym')}</span><span className="flex items-center gap-1"><Utensils size={13} className="text-diet" /> {t('Diet followed')}</span><span className="flex items-center gap-1"><span className="h-2 w-2 rounded-full bg-danger" /> {t('Missed day')}</span><span className="flex items-center gap-1"><Scale size={13} className="text-weight" /> {t('Weight')}</span><span className="flex items-center gap-1"><Image size={13} className="text-photo" /> {t('Progress Photos')}</span></div></div>
}
