import { useState } from 'react'
import { Award, Target } from 'lucide-react'
import { useApp } from '../data/context'
import { Panel, ProgressBar, SectionHead, Field, inputClass } from '../components/shared'
import { Button } from '../components/ui/button'
import { adherence, gymCount, monthStartKey, weekStartKey, weights } from '../lib/stats'
import { dateLabel, formatNumber, todayKey, weightDisplay, weightInputKg } from '../lib/utils'
import { tr } from '../lib/i18n'

export function GoalsPage() {
  const { data, saveSettings } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [target, setTarget] = useState(s.targetWeightKg === undefined ? '' : String(Number(weightDisplay(s.targetWeightKg, s.weightUnit).toFixed(1))))
  const [weekly, setWeekly] = useState(String(s.weeklyGymGoal)), [monthly, setMonthly] = useState(String(s.monthlyGymGoal)), [dietGoal, setDietGoal] = useState(String(s.dietGoal))
  const today = todayKey(), latest = weights(data.days).at(-1), gymWeek = gymCount(data.days, weekStartKey(today, s.weekStart), today), gymMonth = gymCount(data.days, monthStartKey(today), today), diet = adherence(data.days)
  const save = () => void saveSettings({ ...s, targetWeightKg: target && Number(target) > 0 ? weightInputKg(Number(target), s.weightUnit) : undefined, weeklyGymGoal: Math.max(1, Math.min(7, Number(weekly) || 1)), monthlyGymGoal: Math.max(1, Math.min(31, Number(monthly) || 1)), dietGoal: Math.max(1, Math.min(100, Number(dietGoal) || 1)) })
  const records = data.exercises.map(exercise => { const sets = data.workouts.flatMap(w => w.exercises.filter(e => e.exerciseId === exercise.id).flatMap(e => e.sets.map(set => ({ ...set, date: w.date })))); const max = sets.reduce((best, set) => set.weightKg !== undefined && (!best || set.weightKg > best.weightKg!) ? set : best, null as (typeof sets)[number] | null); const volume = data.workouts.reduce((sum, w) => sum + w.exercises.filter(e => e.exerciseId === exercise.id).reduce((v, e) => v + e.sets.reduce((x, set) => x + set.reps * (set.weightKg ?? 0), 0), 0), 0); return { exercise, max, volume } }).filter(r => r.max || r.volume)
  return <div className="page-enter space-y-6"><SectionHead title={t('Goals & Records')} />
    <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><Panel><SectionHead title={t('Goals')} /><div className="grid grid-cols-2 gap-3"><Field label={`${t('Target weight')} · ${s.weightUnit}`}><input className={inputClass} type="number" min="1" step="0.1" value={target} onChange={e => setTarget(e.target.value)} placeholder={t('Optional')} /></Field><Field label={t('Weekly gym goal')}><input className={inputClass} type="number" min="1" max="7" value={weekly} onChange={e => setWeekly(e.target.value)} /></Field><Field label={t('Monthly gym goal')}><input className={inputClass} type="number" min="1" max="31" value={monthly} onChange={e => setMonthly(e.target.value)} /></Field><Field label={`${t('Diet goal')} · %`}><input className={inputClass} type="number" min="1" max="100" value={dietGoal} onChange={e => setDietGoal(e.target.value)} /></Field></div><Button className="mt-4" onClick={save}>{t('Save')}</Button></Panel><Panel><SectionHead title={t('On track')} /><div className="space-y-5">{[{ label: t('Weekly gym goal'), value: gymWeek, goal: s.weeklyGymGoal, text: `${gymWeek} / ${s.weeklyGymGoal}` }, { label: t('Monthly gym goal'), value: gymMonth, goal: s.monthlyGymGoal, text: `${gymMonth} / ${s.monthlyGymGoal}` }, { label: t('Diet goal'), value: diet, goal: s.dietGoal, text: `${diet}% / ${s.dietGoal}%` }].map(g => <div key={g.label}><div className="mb-2 flex justify-between text-xs"><span className="text-muted">{g.label}</span><strong>{g.text}</strong></div><ProgressBar value={g.value / g.goal * 100} /></div>)}{s.targetWeightKg && latest && <p className="flex items-center gap-2 text-xs text-muted"><Target size={14} /> {formatNumber(weightDisplay(Math.abs(latest.kg - s.targetWeightKg), s.weightUnit), s.language, 1)} {s.weightUnit} {t('from target')}</p>}</div></Panel></div>
    <Panel><SectionHead title={t('Personal records')} description={t('Highest logged weight for each exercise, with total training volume.')} />{records.length ? <div className="grid gap-3 sm:grid-cols-2">{records.map(r => <div key={r.exercise.id} className="flex items-start gap-3 rounded-xl border border-line bg-surface-2 p-4"><Award size={19} className="mt-0.5 text-accent" /><div><p className="text-sm font-bold">{r.exercise.name}</p><p className="mt-1 text-lg font-bold">{r.max?.weightKg !== undefined ? `${formatNumber(weightDisplay(r.max.weightKg, s.weightUnit), s.language, 1)} ${s.weightUnit}` : '—'}</p><p className="text-xs text-muted">{r.max ? dateLabel(r.max.date, s.language) : ''} · {formatNumber(weightDisplay(r.volume, s.weightUnit), s.language)} {s.weightUnit} {t('Volume').toLowerCase()}</p></div></div>)}</div> : <p className="py-8 text-center text-sm text-muted">{t('Personal records appear after you log exercise sets in Workouts.')}</p>}</Panel>
  </div>
}
