import { useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useApp } from '../data/context'
import type { MeasurementKey } from '../data/types'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Empty, Field, inputClass, Panel, SectionHead, textareaClass } from '../components/shared'
import { dateLabel, formatNumber, lengthDisplay, lengthInputCm, todayKey, uid } from '../lib/utils'
import { tr } from '../lib/i18n'

const keys: MeasurementKey[] = ['waist', 'chest', 'shoulders', 'arms', 'thighs', 'hips']
export function MeasurementsPage() {
  const { data, saveMeasurement, deleteMeasurement } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [open, setOpen] = useState(false), [date, setDate] = useState(todayKey()), [values, setValues] = useState<Record<string, string>>({}), [customName, setCustomName] = useState(''), [customValue, setCustomValue] = useState(''), [notes, setNotes] = useState('')
  const [metric, setMetric] = useState<string>('waist')
  const history = [...data.measurements].sort((a, b) => b.date.localeCompare(a.date))
  const customKeys = [...new Set(history.flatMap(m => Object.keys(m.custom)))].sort()
  const chartPoints = [...history].reverse().map(m => ({ date: m.date, value: keys.includes(metric as MeasurementKey) ? m.values[metric as MeasurementKey] : m.custom[metric] })).filter((p): p is { date: string; value: number } => p.value !== undefined).map(p => ({ date: p.date, value: Number(lengthDisplay(p.value, s.lengthUnit).toFixed(1)) }))
  const save = async () => { const standard = Object.fromEntries(keys.filter(k => values[k] && Number(values[k]) > 0).map(k => [k, lengthInputCm(Number(values[k]), s.lengthUnit)])); const custom = customName && Number(customValue) > 0 ? { [customName.trim()]: lengthInputCm(Number(customValue), s.lengthUnit) } : {}; if (!Object.keys(standard).length && !Object.keys(custom).length) return; await saveMeasurement({ id: uid(), date, values: standard, custom, notes }); setOpen(false); setValues({}); setCustomName(''); setCustomValue(''); setNotes('') }
  const summary = (key: MeasurementKey) => { const observed = history.filter(m => m.values[key] !== undefined); return { latest: observed[0]?.values[key], earliest: observed.at(-1)?.values[key], count: observed.length } }
  return <div className="page-enter space-y-6"><SectionHead eyebrow={t('BODY / DETAILS')} title={t('Body measurements')} description={t('Optional measurements, kept separate from your daily routine.')} action={<Button onClick={() => setOpen(true)}><Plus size={17} />{t('New measurement')}</Button>} />
    {history.length > 0 && <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{keys.map(k => { const x = summary(k); return <Panel key={k} className="p-4"><p className="text-xs text-muted">{t(k[0].toUpperCase() + k.slice(1))}</p><p className="mt-2 text-lg font-bold">{x.latest !== undefined ? `${formatNumber(lengthDisplay(x.latest, s.lengthUnit), s.language, 1)} ${s.lengthUnit}` : '—'}</p>{x.count > 1 && x.latest !== undefined && x.earliest !== undefined && <p className="mt-1 text-xs text-muted">{formatNumber(lengthDisplay(x.latest - x.earliest, s.lengthUnit), s.language, 1)} {s.lengthUnit} {t('change')}</p>}</Panel> })}</div>}
    {history.length > 0 && <Panel><SectionHead title={t('Measurement trend')} action={<select aria-label={t('Measurement trend')} className={`${inputClass} w-auto min-w-36`} value={metric} onChange={e => setMetric(e.target.value)}>{[...keys, ...customKeys].map(k => <option key={k} value={k}>{t(k[0].toUpperCase() + k.slice(1))}</option>)}</select>} />{chartPoints.length ? <div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartPoints} margin={{ top: 12, right: 15, left: -20, bottom: 0 }}><CartesianGrid stroke="var(--line)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="date" tickFormatter={v => dateLabel(v, s.language, { month: 'short', day: 'numeric' })} tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false} domain={['auto', 'auto']} /><Tooltip labelFormatter={v => dateLabel(String(v), s.language)} formatter={v => [`${v} ${s.lengthUnit}`, t('Body measurements')]} /><Line dataKey="value" type="monotone" stroke="var(--accent)" strokeWidth={2.5} dot={{ r: 4, fill: 'var(--accent)', strokeWidth: 0 }} /></LineChart></ResponsiveContainer></div> : <p className="py-12 text-center text-sm text-muted">{t('No measurements for this metric yet.')}</p>}</Panel>}
    <Panel><SectionHead title={t('History')} />{history.length ? <div className="divide-y divide-line">{history.map(m => <div key={m.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-semibold">{dateLabel(m.date, s.language)}</p><p className="mt-1 text-xs text-muted">{[...Object.entries(m.values), ...Object.entries(m.custom)].map(([k, v]) => `${t(k[0].toUpperCase() + k.slice(1))} ${formatNumber(lengthDisplay(v, s.lengthUnit), s.language, 1)} ${s.lengthUnit}`).join(' · ')}</p>{m.notes && <p className="mt-1 text-xs text-muted">{m.notes}</p>}</div><Button variant="ghost" size="icon" aria-label="Delete measurement" onClick={() => { if (confirm('Delete this measurement?')) void deleteMeasurement(m.id) }}><Trash2 size={16} /></Button></div>)}</div> : <Empty title={t('No measurements yet')} detail={t('Add only the measurements that matter to you.')} />}</Panel>
    <Dialog open={open} onOpenChange={setOpen} title={t('New measurement')}><div className="space-y-4"><Field label={t('Date')}><input type="date" className={inputClass} value={date} onChange={e => setDate(e.target.value)} /></Field><div className="grid grid-cols-2 gap-3">{keys.map(k => <Field key={k} label={`${t(k[0].toUpperCase() + k.slice(1))} · ${s.lengthUnit}`}><input className={inputClass} type="number" min="0" step="0.1" value={values[k] ?? ''} onChange={e => setValues(v => ({ ...v, [k]: e.target.value }))} /></Field>)}</div><div className="grid grid-cols-2 gap-3"><Field label={t('Custom measurement')}><input className={inputClass} value={customName} onChange={e => setCustomName(e.target.value)} placeholder="Neck" /></Field><Field label={s.lengthUnit}><input className={inputClass} type="number" min="0" step="0.1" value={customValue} onChange={e => setCustomValue(e.target.value)} /></Field></div><Field label={t('Notes')}><textarea className={textareaClass} value={notes} onChange={e => setNotes(e.target.value)} /></Field><Button className="w-full" onClick={() => void save()}>{t('Save')}</Button></div></Dialog>
  </div>
}
