import { useEffect, useState } from 'react'
import { Camera, Check, Plus, Trash2 } from 'lucide-react'
import { ReactCompareSlider, ReactCompareSliderImage } from 'react-compare-slider'
import { useApp } from '../data/context'
import type { PhotoCategory } from '../data/types'
import { repository } from '../data/repository'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Empty, Field, inputClass, Panel, SectionHead, Segmented, textareaClass } from '../components/shared'
import { dateLabel, formatNumber, parseDate, todayKey, uid, weightDisplay, weightInputKg } from '../lib/utils'
import { tr } from '../lib/i18n'

export function PhotosPage() {
  const { data, savePhoto, deletePhoto } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [urls, setUrls] = useState<Record<string, string>>({}), [open, setOpen] = useState(false), [file, setFile] = useState<File | null>(null), [date, setDate] = useState(todayKey()), [category, setCategory] = useState<PhotoCategory>('Front'), [weight, setWeight] = useState(''), [bodyFat, setBodyFat] = useState(''), [notes, setNotes] = useState(''), [chosen, setChosen] = useState<string[]>([]), [mode, setMode] = useState<'side' | 'slider'>('side')
  useEffect(() => { let disposed = false; const created: string[] = []; void Promise.all(data.photos.map(async p => { const blob = await repository.getPhotoBlob(p.id); if (!blob || disposed) return; const url = URL.createObjectURL(blob); created.push(url); setUrls(prev => ({ ...prev, [p.id]: url })) })); return () => { disposed = true; created.forEach(URL.revokeObjectURL) } }, [data.photos])
  const photos = [...data.photos].sort((a, b) => b.date.localeCompare(a.date))
  const selected = chosen.map(id => data.photos.find(p => p.id === id)).filter((p): p is NonNullable<typeof p> => !!p).sort((a, b) => a.date.localeCompare(b.date))
  const toggle = (id: string) => setChosen(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev.slice(-1), id])
  const validPhoto = file && ['image/jpeg', 'image/png', 'image/webp', 'image/gif'].includes(file.type)
  const save = async () => { if (!file || !validPhoto || !date) return; await savePhoto({ id: uid(), date, category, weightKg: weight ? weightInputKg(Number(weight), s.weightUnit) : undefined, bodyFat: bodyFat ? Number(bodyFat) : undefined, notes, mimeType: file.type }, file); setOpen(false); setFile(null); setWeight(''); setBodyFat(''); setNotes('') }
  const elapsed = selected.length === 2 ? Math.abs(Math.round((parseDate(selected[0].date).getTime() - parseDate(selected[1].date).getTime()) / 86_400_000)) : 0
  const weightDiff = selected.length === 2 && selected[0].weightKg !== undefined && selected[1].weightKg !== undefined ? selected[1].weightKg - selected[0].weightKg : null
  return <div className="page-enter space-y-6"><SectionHead title={t('Progress Photos')} action={<Button onClick={() => setOpen(true)}><Plus size={17} />{t('Upload photo')}</Button>} />
    <Panel><SectionHead title={t('Before & after')} description={t('Select two photos to compare.')} action={<Segmented value={mode} onChange={setMode} options={[{ value: 'side', label: t('Side by side') }, { value: 'slider', label: t('Slider') }]} />} />{selected.length === 2 && urls[selected[0].id] && urls[selected[1].id] ? <><div className={mode === 'side' ? 'grid grid-cols-2 gap-3' : ''}>{mode === 'side' ? selected.map(p => <img key={p.id} src={urls[p.id]} alt={`${p.category} progress on ${p.date}`} className="aspect-[3/4] w-full rounded-xl bg-surface-2 object-contain" />) : <div className="mx-auto max-w-2xl overflow-hidden rounded-xl"><ReactCompareSlider itemOne={<ReactCompareSliderImage src={urls[selected[0].id]} alt="Before" />} itemTwo={<ReactCompareSliderImage src={urls[selected[1].id]} alt="After" />} style={{ height: 430 }} /></div>}</div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-sm"><span>{dateLabel(selected[0].date, s.language)} → {dateLabel(selected[1].date, s.language)}</span><span className="text-muted">{formatNumber(elapsed, s.language)} {t('days')}{weightDiff !== null ? ` · ${weightDiff > 0 ? '+' : ''}${formatNumber(weightDisplay(weightDiff, s.weightUnit), s.language, 1)} ${s.weightUnit}` : ''}</span></div></> : <Empty title={t('Select two photos to compare.')} detail={t('Choose any two images from the gallery below.')} />}</Panel>
    <div><SectionHead title={t('Gallery')} />{photos.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{photos.map(p => <div key={p.id} className={`overflow-hidden rounded-2xl border bg-surface ${chosen.includes(p.id) ? 'border-accent' : 'border-line'}`}><button onClick={() => toggle(p.id)} className="relative block w-full text-start"><div className="aspect-[3/4] bg-surface-2">{urls[p.id] ? <img src={urls[p.id]} alt={`${p.category} progress on ${p.date}`} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><Camera className="text-muted" /></div>}</div>{chosen.includes(p.id) && <span className="absolute right-3 top-3 flex h-7 w-7 items-center justify-center rounded-full bg-accent text-accent-ink"><Check size={16} /></span>}</button><div className="flex items-start justify-between gap-2 p-3"><div><p className="text-xs font-bold">{dateLabel(p.date, s.language)}</p><p className="mt-1 text-[11px] text-muted">{t(p.category)}{p.weightKg ? ` · ${formatNumber(weightDisplay(p.weightKg, s.weightUnit), s.language, 1)} ${s.weightUnit}` : ''}</p>{p.notes && <p className="mt-1 line-clamp-2 text-[11px] text-muted">{p.notes}</p>}</div><button aria-label="Delete photo" onClick={() => { if (confirm('Delete this photo?')) { void deletePhoto(p.id); setChosen(v => v.filter(x => x !== p.id)) } }}><Trash2 size={15} className="text-muted hover:text-danger" /></button></div></div>)}</div> : <Empty title={t('No photos yet')} detail={t('Photos are stored on this computer.')} action={<Button onClick={() => setOpen(true)}>{t('Upload photo')}</Button>} />}</div>
    <Dialog open={open} onOpenChange={setOpen} title={t('Upload photo')}><div className="space-y-4"><label className="flex min-h-30 cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-line bg-surface-2 text-sm text-muted"><Camera size={24} />{file ? file.name : t('Choose an image from your computer')}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e => setFile(e.target.files?.[0] ?? null)} /></label>{file && !validPhoto && <p role="alert" className="text-xs text-danger">Use a JPG, PNG, WebP, or GIF image.</p>}<div className="grid grid-cols-2 gap-3"><Field label={t('Date')}><input className={inputClass} type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label={t('Pose / category')}><select className={inputClass} value={category} onChange={e => setCategory(e.target.value as PhotoCategory)}>{(['Front', 'Side', 'Back', 'Other'] as const).map(x => <option key={x}>{x}</option>)}</select></Field><Field label={`${t('Weight')} · ${s.weightUnit}`}><input className={inputClass} type="number" min="1" step="0.1" value={weight} onChange={e => setWeight(e.target.value)} /></Field><Field label={`${t('Body fat estimate')} · %`}><input className={inputClass} type="number" min="0" max="100" step="0.1" value={bodyFat} onChange={e => setBodyFat(e.target.value)} /></Field></div><Field label={t('Notes')}><textarea className={textareaClass} value={notes} onChange={e => setNotes(e.target.value)} /></Field><Button className="w-full" onClick={() => void save()} disabled={!validPhoto}>{t('Save')}</Button></div></Dialog>
  </div>
}
