import { useEffect, useState } from 'react'
import { Database, Download, Upload } from 'lucide-react'
import { useApp } from '../data/context'
import { exportBackup, exportCsv, parseBackup } from '../data/backup'
import { repository } from '../data/repository'
import type { AppData, Settings } from '../data/types'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Field, inputClass, Panel, SectionHead, Segmented } from '../components/shared'
import { tr } from '../lib/i18n'
import { weightDisplay, weightInputKg } from '../lib/utils'

const modules = ['measurements', 'photos', 'goals', 'journey', 'statistics']
export function SettingsPage() {
  const { data, saveSettings, reload } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [includePhotos, setIncludePhotos] = useState(true), [pending, setPending] = useState<{ data: AppData; blobs: Map<string, Blob> } | null>(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const [databasePath, setDatabasePath] = useState(''), [photosPath, setPhotosPath] = useState('')
  useEffect(() => { void repository.storageInfo().then(info => { setDatabasePath(info.databasePath); setPhotosPath(info.photosPath) }).catch(() => {}) }, [])
  const update = (part: Partial<Settings>) => void saveSettings({ ...s, ...part })
  const run = async (task: () => Promise<void>) => { setBusy(true); setMessage(''); try { await task() } catch (e) { setMessage(e instanceof Error ? e.message : 'Operation failed') } finally { setBusy(false) } }
  const importFile = (file?: File) => { if (file) void run(async () => { const parsed = await parseBackup(file); setPending(parsed) }) }
  const replace = () => void run(async () => { if (!pending) return; await repository.replaceAll(pending.data, pending.blobs); await reload(); setPending(null); setMessage(t('Backup restored successfully.')) })
  return <div className="page-enter space-y-6"><SectionHead title={t('Settings')} description={t('Stored in a local XAMPP MySQL database')} />
    <Panel className="flex items-start gap-3 p-4"><Database size={18} className="mt-0.5 shrink-0 text-accent" /><div className="min-w-0"><p className="text-sm font-semibold">{t('XAMPP MySQL database')}</p><code dir="ltr" className="mt-1 block break-all text-xs text-muted">{databasePath || t('Loading…')}</code><p className="mt-2 text-xs text-muted">{t('Progress photos folder')}: <code dir="ltr" className="break-all">{photosPath || t('Loading…')}</code></p></div></Panel>
    <div className="grid gap-5 lg:grid-cols-2"><Panel><SectionHead title={t('Appearance')} /><div className="space-y-5"><div><p className="mb-2 text-xs text-muted">{t('Appearance')}</p><Segmented value={s.theme} onChange={theme => update({ theme })} options={[{ value: 'dark', label: t('Dark') }, { value: 'light', label: t('Light') }]} /></div><div><p className="mb-2 text-xs text-muted">{t('Language')}</p><Segmented value={s.language} onChange={language => update({ language })} options={[{ value: 'en', label: 'English' }, { value: 'ar', label: 'العربية' }]} /></div><div><p className="mb-2 text-xs text-muted">{t('Units')}</p><div className="flex flex-wrap gap-3"><Segmented value={s.weightUnit} onChange={weightUnit => update({ weightUnit })} options={[{ value: 'kg', label: 'kg' }, { value: 'lb', label: 'lb' }]} /><Segmented value={s.lengthUnit} onChange={lengthUnit => update({ lengthUnit })} options={[{ value: 'cm', label: 'cm' }, { value: 'in', label: 'in' }]} /></div></div><div><p className="mb-2 text-xs text-muted">{t('Week starts on')}</p><Segmented value={String(s.weekStart)} onChange={v => update({ weekStart: Number(v) as 0 | 1 })} options={[{ value: '1', label: t('Monday') }, { value: '0', label: t('Sunday') }]} /></div></div></Panel>
      <Panel><SectionHead title={t('Tracking preferences')} /><div className="space-y-4"><Field label={t('Heatmap default')}><select className={inputClass} value={s.heatmapMode} onChange={e => update({ heatmapMode: e.target.value as Settings['heatmapMode'] })}><option value="overall">{t('Overall')}</option><option value="gym">{t('Gym')}</option><option value="diet">{t('Diet')}</option><option value="weight">{t('Weight logging')}</option></select></Field><p className="text-xs font-semibold text-muted">{t('Show optional fields')}</p><div className="grid grid-cols-2 gap-3">{(Object.keys(s.optionalFields) as (keyof Settings['optionalFields'])[]).map(field => <label key={field} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={s.optionalFields[field]} onChange={e => update({ optionalFields: { ...s.optionalFields, [field]: e.target.checked } })} /><span className="capitalize">{t(field === 'sleep' ? 'Sleep hours' : field === 'water' ? 'Water intake' : field === 'photo' ? 'Add photo' : field === 'steps' ? 'Steps' : 'Energy')}</span></label>)}</div><p className="pt-2 text-xs font-semibold text-muted">{t('Navigation modules')}</p><div className="grid grid-cols-2 gap-3">{modules.map(m => <label key={m} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!s.hiddenModules.includes(m)} onChange={e => update({ hiddenModules: e.target.checked ? s.hiddenModules.filter(x => x !== m) : [...s.hiddenModules, m] })} /><span>{t(({ measurements: 'Measurements', photos: 'Progress Photos', goals: 'Goals & Records', journey: 'Journey', statistics: 'Statistics' } as Record<string, string>)[m])}</span></label>)}</div></div></Panel></div>
    <Panel><SectionHead title={t('Goals')} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label={`${t('Target weight')} · ${s.weightUnit}`}><input className={inputClass} key={`${s.weightUnit}-${s.targetWeightKg}`} type="number" min="1" step="0.1" defaultValue={s.targetWeightKg === undefined ? '' : Number(weightDisplay(s.targetWeightKg, s.weightUnit).toFixed(1))} onBlur={e => update({ targetWeightKg: e.target.value && Number(e.target.value) > 0 ? weightInputKg(Number(e.target.value), s.weightUnit) : undefined })} /></Field><Field label={t('Weekly gym goal')}><input className={inputClass} key={s.weeklyGymGoal} type="number" min="1" max="7" defaultValue={s.weeklyGymGoal} onBlur={e => update({ weeklyGymGoal: Math.max(1, Math.min(7, Number(e.target.value) || 1)) })} /></Field><Field label={t('Monthly gym goal')}><input className={inputClass} key={s.monthlyGymGoal} type="number" min="1" max="31" defaultValue={s.monthlyGymGoal} onBlur={e => update({ monthlyGymGoal: Math.max(1, Math.min(31, Number(e.target.value) || 1)) })} /></Field><Field label={`${t('Diet goal')} · %`}><input className={inputClass} key={s.dietGoal} type="number" min="1" max="100" defaultValue={s.dietGoal} onBlur={e => update({ dietGoal: Math.max(1, Math.min(100, Number(e.target.value) || 1)) })} /></Field></div></Panel>
    <Panel><SectionHead title={t('Backup & export')} description={t('A backup file is a portable copy of your local data. Keep one somewhere safe.')} /><div className="flex flex-wrap items-center gap-3"><Button onClick={() => void run(() => exportBackup(data, includePhotos))} disabled={busy}><Download size={16} />{t('Export Backup')}</Button><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-line px-4 text-sm font-semibold hover:bg-surface-2"><Upload size={16} />{t('Import Backup')}<input type="file" accept=".zip,.fitlog.zip,application/zip" className="hidden" onChange={e => { importFile(e.target.files?.[0]); e.target.value = '' }} /></label><label className="flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={includePhotos} onChange={e => setIncludePhotos(e.target.checked)} />{t('Include photos')}</label></div><div className="mt-6 border-t border-line pt-5"><p className="mb-3 text-xs font-semibold text-muted">{t('Export CSV')}</p><div className="flex flex-wrap gap-2">{(['weight', 'attendance', 'measurements', 'workouts'] as const).map(kind => <Button key={kind} variant="secondary" size="sm" onClick={() => exportCsv(data, kind)}><Download size={14} />{t(kind)}</Button>)}</div></div>{message && <p className="mt-4 rounded-xl bg-surface-2 p-3 text-sm" role="status">{message}</p>}</Panel>
    <Dialog open={!!pending} onOpenChange={v => { if (!v) setPending(null) }} title={t('Restore backup?')}><div className="space-y-4"><div className="rounded-xl bg-surface-2 p-4 text-sm"><Database size={20} className="mb-3 text-accent" /><p>{t('This backup contains')} <strong>{pending?.data.days.length ?? 0} {t('days')}</strong>, <strong>{pending?.data.workouts.length ?? 0} {t('Workouts')}</strong>, {t('and')} <strong>{pending?.data.photos.length ?? 0} {t('photos')}</strong>.</p><p className="mt-2 text-muted">{t('Restoring replaces the current local data on this computer. Export a backup first if you need the current data later.')}</p></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setPending(null)}>{t('Cancel')}</Button><Button onClick={replace} disabled={busy}>{t('Replace local data')}</Button></div></div></Dialog>
  </div>
}
