import { useState } from 'react'
import { ChevronDown, Dumbbell, Plus, Trash2 } from 'lucide-react'
import { useApp } from '../data/context'
import type { ExerciseEntry, Workout } from '../data/types'
import { Button } from '../components/ui/button'
import { Dialog } from '../components/ui/dialog'
import { Empty, Field, inputClass, Panel, SectionHead, textareaClass } from '../components/shared'
import { dateLabel, formatNumber, todayKey, uid, weightDisplay, weightInputKg } from '../lib/utils'
import { totalVolume } from '../lib/stats'
import { tr } from '../lib/i18n'

export function WorkoutsPage() {
  const { data, saveWorkout, deleteWorkout, saveExercise, saveDay, saveSettings } = useApp(), s = data.settings, t = (x: string) => tr(x, s.language)
  const [open, setOpen] = useState(false), [date, setDate] = useState(todayKey()), [type, setType] = useState('Push'), [customType, setCustomType] = useState(''), [duration, setDuration] = useState(''), [quality, setQuality] = useState(''), [notes, setNotes] = useState(''), [entries, setEntries] = useState<ExerciseEntry[]>([]), [newExercise, setNewExercise] = useState(''), [weighted, setWeighted] = useState(true), [expanded, setExpanded] = useState<string | null>(null)
  const history = [...data.workouts].sort((a, b) => b.date.localeCompare(a.date))
  const createExercise = async () => { if (!newExercise.trim()) return; const id = uid(); await saveExercise({ id, name: newExercise.trim(), weighted }); setEntries(prev => [...prev, { exerciseId: id, sets: [{ reps: 8, weightKg: weighted ? 0 : undefined }] }]); setNewExercise('') }
  const addEntry = (id: string) => { if (id && !entries.some(e => e.exerciseId === id)) setEntries(prev => [...prev, { exerciseId: id, sets: [{ reps: 8, weightKg: 0 }] }]) }
  const updateSet = (entryIndex: number, setIndex: number, key: 'reps' | 'weightKg', value: number | undefined) => setEntries(prev => prev.map((entry, ei) => ei === entryIndex ? { ...entry, sets: entry.sets.map((set, si) => si === setIndex ? { ...set, [key]: value } : set) } : entry))
  const save = async () => {
    const workoutType = type === '__custom' ? customType.trim() : type
    if (!date || !workoutType) return
    if (type === '__custom' && !s.workoutTypes.includes(workoutType)) await saveSettings({ ...s, workoutTypes: [...s.workoutTypes, workoutType] })
    const workout: Workout = { id: uid(), date, type: workoutType, durationMinutes: duration ? Number(duration) : undefined, quality: quality ? Number(quality) : undefined, notes, exercises: entries.filter(e => e.exerciseId).map(e => ({ ...e, sets: e.sets.filter(set => set.reps > 0) })) }
    await saveWorkout(workout)
    await saveDay({ ...(data.days.find(d => d.date === date) ?? { date, gym: null, diet: null }), gym: 'completed' })
    setOpen(false); setEntries([]); setDuration(''); setQuality(''); setNotes('')
  }
  return <div className="page-enter space-y-6"><SectionHead eyebrow={t('TRAINING / LOG')} title={t('Training history')} description={t('Keep it simple, or add sets and reps when you want the detail.')} action={<Button onClick={() => setOpen(true)}><Plus size={17} />{t('New workout')}</Button>} />
    <div className="grid gap-4">{history.length ? history.map(w => <Panel key={w.id} className="p-0"><button className="flex w-full items-center justify-between gap-3 p-5 text-start" onClick={() => setExpanded(expanded === w.id ? null : w.id)}><div className="flex items-center gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent/10 text-accent"><Dumbbell size={20} /></div><div><p className="font-bold">{t(w.type)}</p><p className="mt-0.5 text-xs text-muted">{dateLabel(w.date, s.language)}{w.durationMinutes ? ` · ${w.durationMinutes} ${t('min')}` : ''}{w.exercises.length ? ` · ${w.exercises.length} ${t('Exercises').toLowerCase()}` : ''}</p></div></div><ChevronDown size={17} className={`text-muted transition-transform ${expanded === w.id ? 'rotate-180' : ''}`} /></button>{expanded === w.id && <div className="border-t border-line px-5 pb-5 pt-3"><div className="space-y-3">{w.exercises.map(entry => <div key={entry.exerciseId} className="flex justify-between gap-3 text-sm"><span className="font-semibold">{data.exercises.find(e => e.id === entry.exerciseId)?.name ?? 'Exercise'}</span><span className="text-muted">{entry.sets.map(set => `${set.reps}×${set.weightKg !== undefined ? `${formatNumber(weightDisplay(set.weightKg, s.weightUnit), s.language, 1)} ${s.weightUnit}` : 'BW'}`).join(' · ')}</span></div>)}</div>{w.notes && <p className="mt-4 text-sm text-muted">{w.notes}</p>}<div className="mt-5 flex items-center justify-between text-xs text-muted"><span>{w.quality ? `${t('Quality')} ${w.quality}/5 · ` : ''}{totalVolume(w) ? `${t('Volume')} ${formatNumber(weightDisplay(totalVolume(w), s.weightUnit), s.language)} ${s.weightUnit}` : ''}</span><Button variant="danger" size="sm" onClick={() => { if (confirm('Delete this workout?')) void deleteWorkout(w.id) }}><Trash2 size={14} />{t('Delete')}</Button></div></div>}</Panel>) : <Empty title={t('No workouts yet')} detail={t('The quickest way to start is a gym check-in. Add a session when you want to track details.')} action={<Button onClick={() => setOpen(true)}>{t('New workout')}</Button>} />}</div>
    <Dialog open={open} onOpenChange={setOpen} title={t('New workout')} wide><div className="space-y-5"><div className="grid grid-cols-2 gap-3"><Field label={t('Date')}><input className={inputClass} type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label={t('Workout type')}><select className={inputClass} value={type} onChange={e => setType(e.target.value)}>{s.workoutTypes.map(x => <option key={x} value={x}>{t(x)}</option>)}<option value="__custom">{t('Custom type')}…</option></select></Field></div>{type === '__custom' && <Field label={t('Custom type')}><input className={inputClass} value={customType} onChange={e => setCustomType(e.target.value)} /></Field>}<div className="grid grid-cols-2 gap-3"><Field label={`${t('Duration')} · ${t('min')}`}><input className={inputClass} type="number" min="1" max="1000" value={duration} onChange={e => setDuration(e.target.value)} /></Field><Field label={`${t('Quality')} · 1–5`}><input className={inputClass} type="number" min="1" max="5" value={quality} onChange={e => setQuality(e.target.value)} /></Field></div>
      <div className="border-t border-line pt-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-bold">{t('Exercises')}</p><span className="text-xs text-muted">{t('Optional')}</span></div>{entries.map((entry, ei) => { const exercise = data.exercises.find(e => e.id === entry.exerciseId); return <div key={entry.exerciseId} className="mb-3 rounded-xl border border-line bg-surface-2 p-3"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">{exercise?.name}</p><button aria-label="Remove exercise" onClick={() => setEntries(v => v.filter((_, i) => i !== ei))}><Trash2 size={15} className="text-muted" /></button></div><div className="space-y-2">{entry.sets.map((set, si) => <div key={si} className="grid grid-cols-[2rem_1fr_1fr_2rem] items-center gap-2"><span className="text-xs text-muted">{si + 1}</span><input aria-label="Reps" className={inputClass} type="number" min="1" value={set.reps} onChange={e => updateSet(ei, si, 'reps', Number(e.target.value))} placeholder={t('Reps')} /><input aria-label="Weight lifted" className={inputClass} type="number" min="0" step="0.5" value={set.weightKg === undefined ? '' : Number(weightDisplay(set.weightKg, s.weightUnit).toFixed(1))} onChange={e => updateSet(ei, si, 'weightKg', e.target.value === '' ? undefined : weightInputKg(Number(e.target.value), s.weightUnit))} placeholder={s.weightUnit} /><button aria-label="Remove set" onClick={() => setEntries(v => v.map((en, i) => i === ei ? { ...en, sets: en.sets.filter((_, j) => j !== si) } : en))}><Trash2 size={15} className="text-muted" /></button></div>)}</div><button className="mt-3 text-xs font-semibold text-accent" onClick={() => setEntries(v => v.map((en, i) => i === ei ? { ...en, sets: [...en.sets, { reps: 8, weightKg: exercise?.weighted ? 0 : undefined }] } : en))}>+ {t('Sets')}</button></div> })}
        <select className={inputClass} value="" onChange={e => addEntry(e.target.value)}><option value="">+ {t('Add exercise')}</option>{data.exercises.filter(e => !entries.some(x => x.exerciseId === e.id)).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select><div className="mt-3 flex gap-2"><input className={inputClass} value={newExercise} onChange={e => setNewExercise(e.target.value)} placeholder={t('Exercise name')} onKeyDown={e => { if (e.key === 'Enter') void createExercise() }} /><Button variant="secondary" onClick={() => void createExercise()}><Plus size={16} /></Button></div><label className="mt-2 flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={weighted} onChange={e => setWeighted(e.target.checked)} /> {t('Track lifted weight')}</label></div>
      <Field label={t('Notes')}><textarea className={textareaClass} value={notes} onChange={e => setNotes(e.target.value)} /></Field><Button className="w-full" onClick={() => void save()}>{t('Save workout')}</Button></div></Dialog>
  </div>
}
